#**Author : Harsha Kumavat**
#**Tathastu Scholar Internship Program - FEB 2022**
## **Data Science & ML Intern**
####Task 1 :Study NumPy and Pandas basics,working and code implementation

**NumPy**

In [ ]:
#To use numpy library we will import it first
import numpy as np

In [ ]:
#Creating 1d numpy array
array_1d = np.array([1,2,3])
array_1d

array([1, 2, 3])

In [ ]:
#We can check the type of numpy array using type
type(array_1d)

numpy.ndarray

In [ ]:
#checking the dimension of numpy array
np.ndim(array_1d)

1

In [ ]:
#creating 2d numpy array
array_2d = np.array([[1,2,3]])
array_2d

array([[1, 2, 3]])

In [ ]:
type(array_2d)

numpy.ndarray

In [ ]:
np.ndim(array_2d)

2

In [ ]:
#creating an 1d array to perform numpy functions
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a.shape

(8,)

In [ ]:
np.ndim(a)

1

In [ ]:
a.size

8

In [ ]:
a.min() #return minimum value from array

1

In [ ]:
a.max() #return maximum value from array

8

In [ ]:
a.mean()

4.5

In [ ]:
a.std()

2.29128784747792

In [ ]:
#initializing numpy array with zeros
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#initializing numpy array with ones
c = np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#initialize numpy array with same number
d = np.full((2,3),7)
d

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
#initializing numpy array with random number
e = np.random.rand(2,3)
e

array([[0.09479213, 0.94860621, 0.79672375],
       [0.84102875, 0.02902458, 0.52164694]])

In [ ]:
f = np.random.randint(1,70,10)
f

array([12, 16, 22, 31, 39,  7, 37, 63, 10, 44])

In [ ]:
#gives the array in the range of 10 to 20 where 20 is exclusive
g = np.arange(10,20)
g

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
#Performing arithmetic operations on array such as addition,subtraction, multiplication, division

In [ ]:
a1 = np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [ ]:
a2 = np.array([[3,1],[1,4]])
a2

array([[3, 1],
       [1, 4]])

In [ ]:
a1 + a2

array([[4, 3],
       [4, 8]])

In [ ]:
a1 - a2

array([[-2,  1],
       [ 2,  0]])

In [ ]:
a1 * a2

array([[ 3,  2],
       [ 3, 16]])

In [ ]:
a1 / a2

array([[0.33333333, 2.        ],
       [3.        , 1.        ]])

In [ ]:
a1 * 2 #scalar multiplication

array([[2, 4],
       [6, 8]])

In [ ]:
#finding transpose of an array
a1

array([[1, 2],
       [3, 4]])

In [ ]:
np.transpose(a1)

array([[1, 3],
       [2, 4]])

In [ ]:
np.ravel(a1)

array([1, 2, 3, 4])

In [ ]:
#Numpy array save and loading

In [ ]:
array1 = np.random.rand(2,2) #creating an array
array1

array([[0.47733885, 0.16740404],
       [0.30548534, 0.44213453]])

In [ ]:
np.save('array_save',array1) # saving array using name array_save

In [ ]:
array2 = np.load('array_save.npy') #loading same array values into another variable
array2

array([[0.47733885, 0.16740404],
       [0.30548534, 0.44213453]])

**Pandas**

In [ ]:
import pandas as pd

In [ ]:
#working with series
series1 = pd.Series([1,2,3,4])
series1

0    1
1    2
2    3
3    4
dtype: int64

Series is a single column of the DataFrame

In [ ]:
#check the type 
type(series1)

pandas.core.series.Series

In [ ]:
#assigning index to series 
series2 = pd.Series([2,3,4,5],index=['a','b','c','d'])
series2

a    2
b    3
c    4
d    5
dtype: int64

In [ ]:
#Another way to assign series
Series3 = pd.Series({'a':100,'b':34,'c':60,'d':90})
Series3

a    100
b     34
c     60
d     90
dtype: int64

In [ ]:
#indexing in series
series1[1] #fetching value present at index 1

2

In [ ]:
series1[:3]

0    1
1    2
2    3
dtype: int64

In [ ]:
series1

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
series1 * 2 # scalar multiplication

0    2
1    4
2    6
3    8
dtype: int64

In [ ]:
series2 + Series3 #series addition

a    102
b     37
c     64
d     95
dtype: int64

In [ ]:
#DataFrame is a collection of Series
df1 = pd.DataFrame({'Grades':['A','C','C','D','A','C','A','D','B','B'],'Marks':[97,66,69,44,92,60,94,39,79,80]})
df1

Grades  Marks
0      A     97
1      C     66
2      C     69
3      D     44
4      A     92
5      C     60
6      A     94
7      D     39
8      B     79
9      B     80

In [ ]:
#head() gives the top 5 rows of dataset by default
df1.head()

Grades  Marks
0      A     97
1      C     66
2      C     69
3      D     44
4      A     92

In [ ]:
#number of rows can be passed in head()
df1.head(2)

Grades  Marks
0      A     97
1      C     66

In [ ]:
#To view bottom 5 rows then tail() is used
df1.tail()

Grades  Marks
5      C     60
6      A     94
7      D     39
8      B     79
9      B     80

In [ ]:
#To view the shape of dataset
df1.shape

(10, 2)

In [ ]:
#To get the summary of dataset
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Grades  10 non-null     object
 1   Marks   10 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 288.0+ bytes


In [ ]:
#to get the descriptive statistics of dataset
df1.describe(include='all') #include = 'all' to include categorical column also

Grades      Marks
count      10  10.000000
unique      4        NaN
top         A        NaN
freq        3        NaN
mean      NaN  72.000000
std       NaN  20.231988
min       NaN  39.000000
25%       NaN  61.500000
50%       NaN  74.000000
75%       NaN  89.000000
max       NaN  97.000000

In [ ]:
df1.groupby('Grades')['Marks'].describe() #grade wise descriptive stats

count       mean       std   min    25%   50%    75%   max
Grades                                                            
A         3.0  94.333333  2.516611  92.0  93.00  94.0  95.50  97.0
B         2.0  79.500000  0.707107  79.0  79.25  79.5  79.75  80.0
C         3.0  65.000000  4.582576  60.0  63.00  66.0  67.50  69.0
D         2.0  41.500000  3.535534  39.0  40.25  41.5  42.75  44.0

In [ ]:
#Fetching values from a specific row and column
df1.iloc[0:3,1]

0    97
1    66
2    69
Name: Marks, dtype: int64

In [ ]:
#Fetching values using loc()
df1.loc[0:4,'Grades']

0    A
1    C
2    C
3    D
4    A
Name: Grades, dtype: object

Difference between iloc() and loc() :
* loc() : loc() is label based data selecting method which means that we have to pass the name of the row or column which we want to select.
* iloc() : iloc() is a indexed based selecting method which means that we have to pass integer index in the method to select specific row/column.

In [ ]:
#Drop a column Marks
df1.drop(columns = 'Marks',axis=1) #to replace in original dataset use inplace = True

Grades
0      A
1      C
2      C
3      D
4      A
5      C
6      A
7      D
8      B
9      B

In [ ]:
#Save pandas dataframe into csv file
df1.to_csv('DataFile')